apiVersion: v1
kind: Pod
metadata:
  name: test-program
  labels:
    requestFrom: agent1node
    applicationName: testApp
spec:
  schedulerName: MyK3SScheduler
  containers:
  - name: test-program
    image: mariopetricevic/simpleapp:1.0.0
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"


